#!/sbin/sh

. "$env"

fstab=$ramdisk/fstab.qcom

f2fs_system_opts="ro"
f2fs_system_flags="wait"

f2fs_data_opts="nosuid,nodev,noatime,nodiratime,discard,inline_xattr"
f2fs_data_flags="wait,encryptable=footer"

f2fs_cache_opts="nosuid,nodev,noatime,nodiratime,discard,inline_xattr"
f2fs_cache_flags="wait"

fstab_get_block() {
	echo "$(awk '$2 == "/'$1'" && $3 == "'$2'" { print $1; exit; }' "$fstab")"
}

fstab_get_line() {
	echo "$(awk '$2 == "/'$1'" && $3 == "'$2'" { print NR; exit; }' "$fstab")"
}

fstab_has() {
	[ "$(fstab_get_block $2 $1)" ] || return 1
}

fstab_check() {
	if fstab_has f2fs $1 || ! fstab_has ext4 $1; then
		return 1
	fi
}

fstab_add() {
	block="$(fstab_get_block $1 ext4)"
	line=$(fstab_get_line $1 ext4)
	[ "$block" ] && [ "$line" ] && {
		sed -i "${line}i$block /$1 f2fs $2 $3" "$fstab" && {
			print "Added f2fs /$1 to fstab"
		}
	}
}

fstab_check system && fstab_add system "$f2fs_system_opts" "$f2fs_system_flags"
fstab_check data && fstab_add data "$f2fs_data_opts" "$f2fs_data_flags"
fstab_check cache && fstab_add cache "$f2fs_cache_opts" "$f2fs_cache_flags"

