#!/system/bin/sh
unset LD_PRELOAD
killall dnsmasq 2>/dev/null
echo 0 > /sys/class/android_usb/android0/enable
echo mtp,adb > /sys/class/android_usb/android0/functions
echo 1 > /sys/class/android_usb/android0/enable
iptables-flush
