#!/sbin/sh

OUTFD=/proc/self/fd/$2;
ZIP="$3";
DIR=`dirname "$ZIP"`;

ui_print() {
  until [ ! "$1" ]; do
    echo -e "ui_print $1\nui_print" > $OUTFD;
    shift;
  done;
}

show_progress() { echo "progress $1 $2" > $OUTFD; }
set_perm_recursive() {
  dirs=$(echo $* | awk '{ print substr($0, index($0,$5)) }');
  for i in $dirs; do
    chown -R $1.$2 $i; chown -R $1:$2 $i;
    find "$i" -type d -exec chmod $3 {} +;
    find "$i" -type f -exec chmod $4 {} +;
  done;
}

file_getprop() { grep "^$2" "$1" | cut -d= -f2; }
getprop() { test -e /sbin/getprop && /sbin/getprop $1 || file_getprop /default.prop $1; }
abort() { ui_print "$*"; exit 1; }

mkdir -p /tmp/nethunteruninstall;
cd /tmp/nethunteruninstall;
unzip -o "$ZIP";

ui_print "**********************";
ui_print " Nethunter Uninstaller";
ui_print "**********************";
/tmp/busybox mount /system;
/tmp/busybox mount /data;

# Remove added firmware (folder would only exist if you installed Nethunter)
if [ -d "/system/etc/firmware/rtlwifi" ]; then
  ui_print "@Removing Firmware";
  rm -rf /system/etc/firmware/rtlwifi
  rm -rf /system/etc/firmware/zd1211
  rm -f /system/etc/firmware/ar9170-1.fw
  rm -f /system/etc/firmware/ar9170-2.fw
  rm -f /system/etc/firmware/carl9170.fw
  rm -f /system/etc/firmware/htc_7010.fw
  rm -f /system/etc/firmware/rt73.bin
  rm -f /system/etc/firmware/rt2561.bin
  rm -f /system/etc/firmware/rt2860.bin
  rm -f /system/etc/firmware/rt2870.bin
  rm -f /system/etc/firmware/rt3070.bin
fi

if [ -d "/system/priv-app/Nethunter" ]; then
  ui_print "@Removing Nethunter.apk";
  rm -rf /system/priv-app/Nethunter
fi

if [ -d "/data/data/com.offsec.nethunter" ]; then
  ui_print "@Removing Nethunter chroot/data";
  rm -rf /data/data/com.offsec.nethunter
fi

ui_print "@Uninstall Completed";