#!/sbin/sh

. "$env"

prop=$ramdisk/default.prop

[ -f "$prop" ] || {
	print "Unable to find default.prop!"
	exit 0
}

setprop() {
	grep -q "${1}=" "$prop" && {
		sed -i "s/${1}=.*/${1}=${2}/g" "$prop"
	} || {
		echo "${1}=${2}" >> "$prop"
	}
}

print "Disabling SELinux enforcing..."
setprop ro.build.selinux 1
setprop ro.build.selinux.enforce 0

print "Disabling TIMA..."
setprop ro.config.tima 0
setprop ro.config.rkp false

print "Disabling KNOX..."
setprop ro.config.knox 0
setprop ro.config.kap_default_on false
setprop ro.securestorage.support false

print "Disabling HDCP enforcing..."
setprop wlan.wfd.hdcp disable

exit 0
