#!/bin/bash
# This is a quick helper script to kill mana in the Kali chroot

killall sslsplit; 
killall python; 
killall hostapd; 
killall dhcpd; 
killall tinyproxy; 
killall stunnel4
killall dnsspoof
#killall ruby
service apache2 stop


iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
