#!/bin/bash

mkdir -p "$rootfs"

if [ ! -f /usr/share/debootstrap/scripts/kali-rolling ]; then
	#
	# For those not building on Kali
	echo "Missing kali from debootstrap, downloading it"

	curl "http://git.kali.org/gitweb/?p=packages/debootstrap.git;a=blob_plain;f=scripts/kali;h=50d7ef5b4e9e905cc6da8655416cdf3ef559911e;hb=refs/heads/kali/master" > /usr/share/debootstrap/scripts/kali
	ln -s /usr/share/debootstrap/scripts/kali /usr/share/debootstrap/scripts/kali-rolling
fi


if [ -f /.dockerenv ]; then
	#
	# Docker needs binfmt to run arm.  Without below commands second-stage and chroot will fail
	# http://neophob.com/2014/10/run-arm-binaries-in-your-docker-container-using-boot2docker/
	#
	mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc
	update-binfmts --enable qemu-arm
	#
	# qemu-debootstrap includes foreign and second stage but requires binfmt-support package
	# Also copies qemu-user-static
	#
	qemu-debootstrap --verbose --arch=$build_arch kali-rolling "$rootfs" http://repo.kali.org/kali
	cp /usr/bin/qemu-arm-static "$rootfs/usr/bin/"
else
	debootstrap --foreign --arch $build_arch kali-rolling "$rootfs" http://repo.kali.org/kali
	cp /usr/bin/qemu-arm-static "$rootfs/usr/bin/"
	chroot_do /debootstrap/debootstrap --second-stage
fi

echo "[+] Completed stage 1!"
