#!/bin/bash

cat << EOF > "$rootfs/cleanup"
#!/bin/bash
rm -f /root/.bash_history
apt-get clean
rm -f /var/lib/apt/lists/*
rm -f /0
rm -f /hs_err*
rm -f /third-stage
rm -f /cleanup
rm -f /usr/bin/qemu*
EOF

chmod +x "$rootfs/cleanup"
chroot_do /cleanup

echo "[+] Completed stage 4!"
