#!/sbin/sh

. "$env"

if [ ! -x "/system/xbin/supolicy" ]; then
	print "Could not find supolicy binary, skipping..."
	exit 0
fi

# patch sepolicy for SuperSU
print "Patching the sepolicy for SuperSU..."
LD_LIBRARY_PATH=$LIBDIR /system/xbin/supolicy --file "$ramdisk/sepolicy" "$ramdisk/sepolicy_new"
if [ -f "$ramdisk/sepolicy_new" ]; then
	rm "$ramdisk/sepolicy"
	mv "$ramdisk/sepolicy_new" "$ramdisk/sepolicy"
	chmod 0644 "$ramdisk/sepolicy"
else
	print "Unable to patch the sepolicy, continuing..."
fi
