#!/sbin/sh

. "$env"

# patch sepolicy for SuperSU
print "Patching the sepolicy for SuperSU..."
LD_LIBRARY_PATH=$LIBDIR /system/xbin/supolicy --file "$ramdisk/sepolicy" "$ramdisk/sepolicy_new"
[ -f "$ramdisk/sepolicy_new" ] && {
	rm "$ramdisk/sepolicy"
	mv "$ramdisk/sepolicy_new" "$ramdisk/sepolicy"
	chmod 0644 "$ramdisk/sepolicy"
} || {
	print "Unable to patch the sepolicy, continuing..."
}
