#!/sbin/sh

. "$env"

print "Disabling dm-verity & forced encryption..."

found_fstab=false

for fstab in fstab.*; do
	print "Found fstab: $fstab"
	sed -i "s/,verify\b//g;s/\bverify,//g;s/\bverify\b//g;s/\bforceencrypt=/encryptable=/g" "$fstab"
	found_fstab=true
done

$found_fstab || print "Unable to find the fstab!"

setprop ro.config.dmverity false

exit 0
