#!/sbin/sh
# Kali Nethunter installer

# write the location of the console buffer to /tmp/console for other scripts to use
console="/proc/$$/fd/$2"
echo $console > /tmp/console

progress() {
	echo "set_progress $1" > $console
}

print() {
	echo "ui_print $1" > $console
}

copy() {
	cp -r "$1" "$2"
}

install() {
	rm -f "$2"
	mv "$1" "$2"
}

mount() {
	/tmp/busybox mount $1
}

unmount() {
	/tmp/busybox umount $1
}

extract() {
	rm -rf "$2"
	mkdir "$2"
	unzip -o "$1" -d "$2"
}

symlink() {
	rm "$2"
	ln -s "$1" "$2"
}

tmp=/tmp/nethunter
patchtmp=/tmp/boot-patcher
sutmp=/tmp/supersu

print "#######################################################"
print "##                                                   ##"
print "##  88      a8P          db         88           88  ##"
print "##  88    .88'          d88b        88           88  ##"
print "##  88   88'           d8''8b       88           88  ##"
print "##  88 d88            d8'  '8b      88           88  ##"
print "##  8888'88.         d8YaaaaY8b     88           88  ##"
print "##  88P   Y8b       d8''''''''8b    88           88  ##"
print "##  88     '88.    d8'        '8b   88           88  ##"
print "##  88       Y8b  d8'          '8b  88888888888  88  ##"
print "##                                                   ##"
print "####  ############### Nethunter #######################"

# Clean installer data from previous flashes
rm -rf $tmp $patchtmp $sutmp

# Unpack the installer
extract "$3" $tmp
cd $tmp

progress 0.0
print "@Starting the install process"
install tools/busybox /tmp/busybox
chmod 0755 /tmp/busybox
mount /data
mount /system
progress 0.1

print "@Checking for previous versions of Nethunter"
sh tools/previnstall.sh

progress 0.2

print "@Installing Apps"

install "supersu/vars" "/system/.supersu"
print "Installing SuperSU in system mode"
extract "supersu/supersu.zip" "$sutmp"
progress 0.3
sh "$sutmp/META-INF/com/google/android/update-binary" dummy 1 "$sutmp/supersu.zip"
mount /data
mount /system

progress 0.4

print "Installing Nethunter App"
install "data/app/nethunter.apk" "/data/app/nethunter.apk"
print "Installing Nethunter Terminal"
install "data/app/Term-nh.apk" "/data/app/Term-nh.apk"
print "Installing BlueNMEA"
install "data/app/BlueNMEA.apk" "/data/app/BlueNMEA.apk"
print "Installing Drivedroid Free"
install "data/app/Drivedroid.apk" "/data/app/Drivedroid.apk"
print "Installing Hacker's Keyboard"
install "data/app/Hackerskeyboard.apk" "/data/app/Hackerskeyboard.apk"
print "Installing RFAnalyzer"
install "data/app/RFAnalyzer.apk" "/data/app/RFAnalyzer.apk"
print "Installing Shodan"
install "data/app/Shodan.apk" "/data/app/Shodan.apk"
print "Installing USB Keyboard"
install "data/app/USBKeyboard.apk" "/data/app/USBKeyboard.apk"
print "Installing VNC"
install "data/app/VNC-nh.apk" "/data/app/VNC-nh.apk"
print "Installing RouterKeygen"
install "data/app/RouterKeygen.apk" "/data/app/RouterKeygen.apk"
print "Installing cSploit Nightly"
install "data/app/cSploit-nightly.apk" "/data/app/cSploit-nightly.apk"

progress 0.5

print "@Freeing up some space on /system"
sh tools/cleansystem.sh

print "@Installing nano binary"
sh tools/installnano.sh

print "@Installing Nethunter wallpapers"
sh wallpaper/setwallpaper.sh

progress 0.6

print "@Checking for Busybox"
sh tools/busyboxcheck.sh

print "@Installing Proxdroid"
sh tools/symlinkproxmark3.sh

progress 0.7

print "@Installing Nethunter boot animation"
install "system/media/bootanimation.zip" "/system/media/bootanimation.zip"

print "@Symlinking Kali boot scripts"
symlink "/data/data/com.offsec.nethunter/files/scripts/bootkali" "/system/bin/bootkali"
symlink "/data/data/com.offsec.nethunter/files/scripts/bootkali_login" "/system/bin/bootkali_login"
symlink "/data/data/com.offsec.nethunter/files/scripts/bootkali_bash" "/system/bin/bootkali_bash"

progress 0.8

print "@Patching boot image"
extract "boot-patcher.zip" "$patchtmp"
sh "$patchtmp/META-INF/com/google/android/update-binary" dummy 1 "$tmp/boot-patcher.zip"

progress 0.9

print "@Checking for Kali Chroot in installer...this may take a while..."
copy "data/local/." "/data/local/"
sh tools/extractchroot.sh

unmount /data
unmount /system

print "@Installation complete"
progress 1.0
